project:
  type: website

website:
  title: "My Simple Quarto Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: slides/slides.qmd
        text: Slides   # Added link to your Reveal.js slide deck

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true

resources:
  - reference.bib 
